name: tests
on: push
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
      - name: Merge pull request (if tests pass)
        if: success()
        run: |
          token=$GITHUB_TOKEN
          owner=$(jq -r .repository.owner <<< "$GITHUB_CONTEXT")
          repo=$(jq -r .repository.repo <<< "$GITHUB_CONTEXT")
          pull_number=$(jq -r .pull_request.number <<< "$GITHUB_CONTEXT")

          curl -X PUT \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $token" \
            -d '{"commit_title": "Automatically Merged"}' \
            "https://api.github.com/repos/$owner/$repo/pulls/$pull_number/merge"
